name: apollovm_web_example
description: Web example for the ApolloVM Dart package.
version: 1.1.0
homepage: https://github.com/ApolloVM/apollovm_web_example
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  apollovm: ^0.0.51
  collection: ^1.18.0
  dom_tools: ^2.3.0
  swiss_knife: ^3.2.0
  data_serializer: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^3.0.0

#dependency_overrides:
#  apollovm:
#    path: ../apollovm_dart
