name: apollovm_web_example
description: Web example for the ApolloVM Dart package.
version: 1.0.0
homepage: https://github.com/ApolloVM/apollovm_web_example
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  apollovm: ^0.0.37
  collection: ^1.18.0

dev_dependencies:
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.5
  lints: ^2.1.1
