name: apollovm_web_example
description: Web example for the ApolloVM Dart package.
version: 1.0.0
homepage: https://github.com/ApolloVM/apollovm_web_example
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  apollovm: ^0.0.30
  collection: ^1.15.0

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  lints: ^1.0.0
