part of '../main.dart';

Future<({Object? result, String output, String executedCode})> executeVM(
  String language,
  String code,
  String className,
  String functionName,
  String positionalParametersJson,
  String namedParametersJson,
  bool wasmCompiled,
  bool nullSafetyChecks,
) async {
  // Normalize the entry-point fields the way apollovm 2.23.1 normalizes them
  // for its CLI/MCP callers: trim both, and treat a blank name as "not
  // specified" — an empty class means a top-level function, an empty function
  // means `main`. The runner APIs called below do no trimming of their own, so
  // a stray space typed (or pasted) into a field would otherwise become part
  // of the name and only surface as `Can't find class to execute:  Foo `.
  className = className.trim();
  functionName = functionName.trim();
  if (functionName.isEmpty) functionName = 'main';

  print('-----------------------------------------------------');
  print('>> Execute VM:');
  print('language: $language');
  print('code: <<<\n$code\n>>>');

  var vm = ApolloVM(nullSafetyChecks: nullSafetyChecks);

  var codeUnit = SourceCodeUnit(language, code, id: 'web');

  Object? loadError;
  var loadOK = false;
  try {
    loadOK = await vm.loadCodeUnit(codeUnit);
  } catch (e, s) {
    // A null-safety rejection is already a complete report; wrapping it in
    // `Can't load source!` would bury the findings.
    if (e is NullSafetyError) rethrow;
    loadError = e;
    printError('$e');
    printError('$s');
  }

  if (!loadOK) {
    throw StateError("Can't load source! Language: $language\n\n$loadError");
  }

  positionalParametersJson = positionalParametersJson.trim();
  namedParametersJson = namedParametersJson.trim();

  List? positionalParameters = positionalParametersJson.isNotEmpty
      ? json.decode('[ $positionalParametersJson ]')
      : [];

  Map? namedParameters = namedParametersJson.isNotEmpty
      ? json.decode('{ $namedParametersJson }')
      : {};

  print('positionalParameters: $positionalParameters');
  print('namedParameters: $namedParameters');

  String executedCode;
  var output = StringBuffer();
  ASTValue astValue;

  if (wasmCompiled) {
    var storageWasm = vm.generateAllIn<BytesOutput>('wasm');
    var wasmModules = await storageWasm.allEntries();

    var wasmModule = wasmModules.values.first.entries.first;
    var wasmOutput = wasmModule.value;

    print('Wasm bytes (HEX): \n${hex.encode(wasmOutput.output())}');

    executedCode = wasmOutput.toString(hex: true);
    print('Wasm bytes: <<<\n\n$executedCode\n>>>');

    var vmWasm = ApolloVM();

    var wasmCodeUnit = BinaryCodeUnit(
      'wasm',
      wasmOutput.output(),
      id: 'test.wasm',
      namespace: '',
    );

    var wasmLoad = await vmWasm.loadCodeUnit(wasmCodeUnit);
    if (!wasmLoad) {
      throw StateError("Can't load compiled Wasm!");
    }

    var wasmRunner = vmWasm.createRunner('wasm')!;

    // Map the `print` function in the VM:
    wasmRunner.externalPrintFunction = (o) => output.writeln(o);

    var parameters = [...?positionalParameters, ...?namedParameters?.values];

    var entryPoint = className.isNotEmpty
        ? '$className.$functionName'
        : functionName;

    // Mirror the interpreted path: a class method runs via `executeClassMethod`,
    // a top-level function via `executeFunction`. The Wasm runner resolves a
    // class method (e.g. `Foo.main`) by its method name. (ApolloVM's Wasm
    // backend is alpha and currently compiles only top-level functions, so a
    // class method may not yet be present in the compiled module.)
    try {
      if (className.isNotEmpty) {
        astValue = await wasmRunner.executeClassMethod(
          '',
          className,
          functionName,
          positionalParameters: parameters,
        );
      } else {
        astValue = await wasmRunner.executeFunction(
          '',
          functionName,
          positionalParameters: parameters,
        );
      }
    } on WasmModuleLoadError catch (e) {
      // A page CSP with a `script-src` but no `'wasm-unsafe-eval'` makes the
      // browser refuse `WebAssembly.instantiate()` on the generated bytes. The
      // engine's own message is opaque here, so name the cause.
      var msg = '$e'.toLowerCase();
      if (msg.contains('content security policy') ||
          msg.contains('unsafe-eval') ||
          msg.contains('csp')) {
        throw StateError(
          "The browser refused to compile the Wasm module: this page's "
          "Content-Security-Policy doesn't allow WebAssembly compilation.\n"
          "Its `script-src` directive needs `'wasm-unsafe-eval'`.\n"
          "Tip: run in interpreted mode (uncheck `Wasm compiled`), or serve "
          "this page with a CSP that allows Wasm.\n\n$e",
        );
      }
      rethrow;
    } on StateError catch (e) {
      if (e.message.contains('find function')) {
        throw StateError(
          "Wasm entry point `$entryPoint` not found in the compiled module.\n"
          "ApolloVM's Wasm backend (alpha) currently compiles only top-level "
          "functions, so class methods like `$entryPoint` may not be compiled "
          "to Wasm yet.\nTip: use a top-level `$functionName(...)` function "
          "(clear the class field), or run in interpreted mode.",
        );
      }
      rethrow;
    }
  } else {
    executedCode = code;

    var dartRunner = vm.createRunner(language)!;

    dartRunner.externalPrintFunction = (o) => output.writeln(o);

    try {
      if (className.isNotEmpty) {
        // `classInstanceFields: {}` provides a fresh, field-less instance, the
        // way `ApolloRuntime` (the CLI/MCP entry path) does — without it only a
        // `static` method can run, and a plain `int run(...)` fails with
        // `Can't call non-static method 'Foo.run' without a class instance`.
        // A static method is unaffected by the empty instance.
        astValue = await dartRunner.executeClassMethod(
          '',
          className,
          functionName,
          positionalParameters: positionalParameters,
          namedParameters: namedParameters,
          classInstanceFields: const {},
        );
      } else {
        astValue = await dartRunner.executeFunction(
          '',
          functionName,
          positionalParameters: positionalParameters,
          namedParameters: namedParameters,
        );
      }
    } catch (e) {
      // The runner reports an unresolved entry point with the name it looked
      // for and nothing else. Say what the source actually declares instead —
      // the same shape apollovm 2.23.3 gives the MCP tools.
      var detailed = entryPointNotFoundMessage(
        '$e',
        codeUnit.root,
        className,
        functionName,
      );
      if (detailed != null) throw StateError(detailed);
      rethrow;
    }
  }

  var result = await astValue.getValueNoContext();

  print("RESULT: $result");

  var outputStr = output.toString();
  print('OUTPUT: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<');
  print(outputStr);
  print('>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>');

  return (result: result, output: outputStr, executedCode: executedCode);
}

/// Rewrites an "entry point not resolved" runner error ([error], the caught
/// error's `toString()`) into a message naming what [root] actually declares.
/// Returns `null` for any other error, which must surface unchanged.
///
/// The runner has three of these, all of which only repeat the name that was
/// looked for: a missing class (`Can't find class to execute: Bar->main`), a
/// missing top-level function (`Can't find function to execute> functionName:
/// nope`) and a missing method in a class that does exist (`Can't find entry
/// function: nope`). The last one is raised by the entry-point call itself, not
/// by a call inside the program, so matching it here cannot swallow a genuine
/// runtime error from the executed code.
String? entryPointNotFoundMessage(
  String error,
  ASTRoot? root,
  String className,
  String functionName,
) {
  if (root == null) return null;

  var missingClass = error.contains("Can't find class to execute");
  var missingFunction =
      error.contains("Can't find function to execute") ||
      (className.isNotEmpty &&
          error.contains("Can't find entry function: $functionName"));

  if (!missingClass && !missingFunction) return null;

  var entryPoints = declaredEntryPoints(root);
  var declared = entryPoints.isEmpty
      ? 'The source declares no functions.'
      : 'Declared: ${entryPoints.map((e) => '`$e`').join(', ')}.';

  if (missingClass) {
    var classes = root.classesNames;
    var known = classes.isEmpty
        ? 'The source declares no classes.'
        : 'Declared classes: ${classes.map((c) => '`$c`').join(', ')}.';
    return 'Entry class `$className` not found in the source. $known\n'
        '$declared\n'
        'Tip: clear the Class field to run a top-level `$functionName(…)`.';
  }

  var scope = className.isNotEmpty
      ? 'Entry method `$className.$functionName`'
      : 'Entry function `$functionName`';

  return '$scope not found in the source. $declared\n'
      'Tip: the Function field selects the entry point (blank means `main`), '
      'and the Class field scopes it to a class method.';
}

/// Every callable [root] declares, as `Ret name(T a)` signatures — top-level
/// functions first, then class methods qualified with their class.
List<String> declaredEntryPoints(ASTRoot root) => [
  for (var set in root.functions)
    for (var f in set.functions) _entrySignature(f),
  for (var clazz in root.classes)
    for (var set in clazz.functions)
      for (var f in set.functions) _entrySignature(f, className: clazz.name),
];

/// Formats a declaration as `Ret name(T1 a, T2 b)`, qualified with [className]
/// when it is a class method.
String _entrySignature(ASTInvocableDeclaration f, {String? className}) {
  var params = [
    for (var p in f.parameters.allParameters) '${p.type.name} ${p.name}',
  ].join(', ');

  var name = className != null ? '$className.${f.name}' : f.name;
  var returnType = f.returnType.name;
  var prefix = returnType.isEmpty ? '' : '$returnType ';

  return '$prefix$name($params)';
}

Future<({bool ok, BytesOutput output})> compileToWasm(
  String language,
  String code,
  bool nullSafetyChecks,
) async {
  print('-----------------------------------------------------');
  print('>> Compile to Wasm:');
  print('language: $language');
  print('code: <<<\n$code\n>>>');

  var vm = ApolloVM(nullSafetyChecks: nullSafetyChecks);

  var codeUnit = SourceCodeUnit(language, code, id: 'web');

  Object? loadError;
  var loadOK = false;
  try {
    loadOK = await vm.loadCodeUnit(codeUnit);
  } catch (e, s) {
    // A null-safety rejection is already a complete report; wrapping it in
    // `Can't load source!` would bury the findings.
    if (e is NullSafetyError) rethrow;
    loadError = e;
    printError('$e');
    printError('$s');
  }

  if (!loadOK) {
    throw StateError("Can't load source! Language: $language\n\n$loadError");
  }

  var storageWasm = vm.generateAllIn<BytesOutput>('wasm');
  var wasmModules = await storageWasm.allEntries();

  var wasmModule = wasmModules.values.first.entries.first;
  var wasmOutput = wasmModule.value;

  print('Wasm bytes: <<<\n\n${wasmOutput.toString(hex: true)}\n>>>');

  return (ok: true, output: wasmOutput);
}

Future<String?> convertCode(
  String fromLanguage,
  String code,
  String toLanguage,
  bool nullSafetyChecks,
) async {
  print('Converting from `$fromLanguage` to `$toLanguage`');

  print(code);

  var vm = ApolloVM(nullSafetyChecks: nullSafetyChecks);

  var codeUnit = SourceCodeUnit(fromLanguage, code, id: 'convert');

  var loadOK = false;
  try {
    loadOK = await vm.loadCodeUnit(codeUnit);
  } catch (e, s) {
    if (e is NullSafetyError) rethrow;
    printError('$e');
    printError('$s');
  }

  if (!loadOK) {
    throw StateError("Can't load source! Language: $fromLanguage");
  }

  var codeStorage = vm.generateAllCodeIn(toLanguage);
  var allSources = await codeStorage.writeAllSources();

  var code2 = allSources.toString();

  print(code2);

  code2 = code2.replaceAll(RegExp(r'<<<<[^>]+>>>>'), '').trim();

  return code2;
}

/// The message of an [UnsupportedSyntaxError], without the `[Unsupported
/// Syntax]` tag that its `toString()` prepends.
///
/// ApolloVM 1.9.0 throws this at *generation* time when the target language has
/// no equivalent construct — e.g. an `extension` into Java/JS/TS/Python/Go/Lua,
/// or an extension *getter* into C# (which has no extension property).
String unsupportedSyntaxDetail(UnsupportedSyntaxError e) {
  var message = '${e.message}';
  const tag = '[Unsupported Syntax] ';
  return message.startsWith(tag) ? message.substring(tag.length) : message;
}

/// Source languages ApolloVM can both parse and generate. These are the
/// transpilation targets for the "Convert to all languages" feature. Wasm is a
/// binary compile target (offered via "Download Wasm"), not a source target.
///
/// Go both parses and generates. Its buffer produces no LSP document symbols
/// yet, so the Outline panel stays empty for a `.go` file, but it runs and
/// transpiles like any other source language.
const conversionLanguages = <String>[
  'dart',
  'java11',
  'kotlin',
  'javascript',
  'typescript',
  'lua',
  'python',
  'csharp',
  'go',
];

/// Transpiles [code] (parsed as [fromLanguage]) to every other language in
/// [conversionLanguages]. The source is parsed once, then generated for each
/// target. Returns a map of target language -> generated source, with an
/// `ERROR: ...` message for any target (or the parse step) that fails.
Future<Map<String, String>> convertCodeToAllLanguages(
  String fromLanguage,
  String code,
  bool nullSafetyChecks,
) async {
  var vm = ApolloVM(nullSafetyChecks: nullSafetyChecks);

  Object? loadError;
  var loaded = false;
  try {
    loaded = await vm.loadCodeUnit(
      SourceCodeUnit(fromLanguage, code, id: 'convert'),
    );
  } catch (e, s) {
    // A null-safety rejection is already a complete report; wrapping it in
    // `Can't load source!` would bury the findings.
    if (e is NullSafetyError) rethrow;
    loadError = e;
    printError('$e');
    printError('$s');
  }

  var results = <String, String>{};
  for (var target in conversionLanguages) {
    if (target == fromLanguage) continue;

    if (!loaded) {
      results[target] =
          "ERROR: can't parse `$fromLanguage` source.\n\n$loadError";
      continue;
    }

    try {
      var codeStorage = vm.generateAllCodeIn(target);
      var allSources = await codeStorage.writeAllSources();
      var generated = allSources
          .toString()
          .replaceAll(RegExp(r'<<<<[^>]+>>>>'), '')
          .trim();
      results[target] = generated.isEmpty ? '(no output)' : generated;
    } on UnsupportedSyntaxError catch (e) {
      results[target] =
          "UNSUPPORTED: `$target` has no equivalent construct.\n\n"
          '${unsupportedSyntaxDetail(e)}';
    } catch (e) {
      results[target] = 'ERROR converting to `$target`:\n\n$e';
    }
  }

  return results;
}

void printError(Object? o) {
  console.error('$o'.toJS);
}
